name: CI

on:
  pull_request:
    branches:
      - "*"

  push:
    branches:
      - test-nginx-1
jobs:

  
  rancher-build:
    runs-on: ubuntu-latest
    env:
      PLATFORMS: linux/amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: build
        run: |
          dapper build